<!DOCTYPE html>
<html>
<head>
    <title>${content.title}</title>
    <meta charset="UTF-8">
</head>
<body>
<header>
    <h1>${content.title}</h1>
</header>

<main>
    <#list published_posts as post>
        <article>
            <h2><a href="${post.uri}">${post.title}</a></h2>
            <p>${post.date?string("yyyy-MM-dd")}</p>
            <p>${post.body}</p>
        </article>
    </#list>
</main>

<footer>
    <p>Generated by JBake</p>
</footer>
</body>
</html>